### ISSUE TITLE
how to getTokenAccountOwner

### ISSUE THREAD

**Issue by yangyile1990** [blocto/solana-go-sdk#146]
I see the https://solscan.io/account/7N6Y6cYRdVuD2ViCk6imDMpjsvd8L83jM2hmY7GXVVXX

address = 7N6Y6cYRdVuD2ViCk6imDMpjsvd8L83jM2hmY7GXVVXX

const publicKey = new solanaWeb3.PublicKey(address);
const tokenAccountInfo = await connection.getAccountInfo(publicKey);
const owner = tokenAccountInfo.data.parsed.info.owner;

want owner = g6C2kzzxGa653aAiHmN8HTntAAPjeSD5C191h8rdqrQ

while when i see the golang sdk.

type AccountInfo struct {
	Lamports   uint64
	Owner      common.PublicKey
	Executable bool
	RentEpoch  uint64
	Data       []byte
}

how can I get   data.parsed.info.owner? 

too hard to use.

**Comment by yihau** [comment]
https://blocto.github.io/solana-go-sdk/tour/get-token-account.html

**Comment by yangyile1990** [comment]
cool! very useful.
