### ISSUE TITLE
How to create stake account?

### ISSUE THREAD

**Issue by skport** [blocto/solana-go-sdk#152]
https://solanacookbook.com/references/staking.html#create-stake-account

According to the solana cookbook, I need to use StakeProgram.createAccount.
How can I do this in this SDK?

**Comment by yihau** [comment]
thank you for bumping this up. I just realized that I missed the doc. let me write some quick examples for you. 
(btw, the instructions can check here https://github.com/blocto/solana-go-sdk/blob/main/program/stake/instruction.go#L55)

**Comment by yihau** [comment]
https://blocto.github.io/solana-go-sdk/programs/stake/initialize-account.html

btw, you will need to use the latest version.

```
go get github.com/blocto/solana-go-sdk@HEAD
```
