### ISSUE TITLE
UpdateMetadataAccount returning deprecated error

### ISSUE THREAD

**Issue by Nunompf** [blocto/solana-go-sdk#154]
Hello.

The instruction in metaplex/token_metadata 'UpdateMetadataAccount' is returning a deprecated error:
`2024/02/21 10:00:18 failed to send tx, err: {"code":-32002,"message":"Transaction simulation failed: Error processing Instructionrogram error: 0x4b","data":{"accounts":null,"err":{"InstructionError":[0,{"Custom":75}]},"logs":["Program metaqbxxUerdq28cj1RbAWkbt518x1s invoke [1]","Program log: This instruction was deprecated in a previous release and is now removed","Program metaqbxxUerYQm3ybzjb6a8bt518x1s consumed 2371 of 200000 compute units","Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: custom p: 0x4b"],"returnData":null,"unitsConsumed":0}}`

I'm also using the example provided in the docs [https://github.com/blocto/solana-go-sdk/blob/main/docs/_examples/program/metaplex/token-metadata/update-metadata/main.go](url)

I belive this could be because in the official metaplex docs they have upgraded the instruction? As seen in here [https://docs.metaplex.com/programs/token-metadata/changelog/v1.1](url)

**Comment by yihau** [comment]
thank you for pointing this out. I will update them soon!

**Comment by yihau** [comment]
I added `UpdateMetadataAccountV2`. this one should be fixed in v1.27.0!
