### ISSUE TITLE
How do I initiate a USDT SPL transfer transaction?

### ISSUE THREAD

**Issue by pengbotter** [blocto/solana-go-sdk#158]
How do I initiate a USDT SPL transfer transaction?

**Comment by yihau** [comment]
https://blocto.github.io/solana-go-sdk/tour/token-transfer.html

**Comment by pengbotter** [comment]
> https://blocto.github.io/solana-go-sdk/tour/token-transfer.html

Can feePayer and alice be aliceTokenRandomTokenPubkey?

**Comment by pengbotter** [comment]
I hope to implement a transfer process by only passing in the sender and receiver, the mint address, and the sending amount.
