### ISSUE TITLE
transfer

### ISSUE THREAD

**Issue by daijun168** [blocto/solana-go-sdk#27]
Is there any difference between the types.NewMessage and types.CreateRawTransactionParam

**Comment by daijun168** [comment]
I prefer golang!&nbsp;
Transfer has feePayer and FROM, from &nbsp;isn't payer?And there was an error in the transfer:




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "portto/solana-go-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月19日(星期二) 晚上9:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [portto/solana-go-sdk] transfer (Issue #27)





 
cool!
 
if you don't mind read js code. there is a web3 project, you can take a look too.
 
https://github.com/yihau/solana-web3-demo/blob/main/README.en.md
 
feel free to open another issue to ask me any questions about solana.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by daijun168** [comment]
I prefer golang! 
Transfer has feePayer and FROM, from &nbsp;isn't payer?And there was an error in the transfer:
2021/10/20 15:25:22 failed to send tx, err: rpc response error: {"code":-32002,"message":"Transaction simulation failed: Attempt to debit an account but found no record of a prior credit
.","data":{"accounts":null,"err":"AccountNotFound","logs":[]}}





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "portto/solana-go-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月19日(星期二) 晚上9:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [portto/solana-go-sdk] transfer (Issue #27)





 
cool!
 
if you don't mind read js code. there is a web3 project, you can take a look too.
 
https://github.com/yihau/solana-web3-demo/blob/main/README.en.md
 
feel free to open another issue to ask me any questions about solana.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yihau** [comment]
in solana, from and payer can be different address but also you can set them in the same.
`Transaction simulation failed: Attempt to debit an account but found no record of a prior credit` => this error usually happened when your account don't have any SOL and you want to charge to it.
check your from and feePayer has enough SOL. (you can use airdrop to get some)

**Comment by daijun168** [comment]
When "from" and "feePayer" coexist, "from" pays fees, and "feePayer" pays sol?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "portto/solana-go-sdk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月20日(星期三) 下午3:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [portto/solana-go-sdk] transfer (Issue #27)





 
in solana, from and payer can be different address but also you can set them in the same.
 Transaction simulation failed: Attempt to debit an account but found no record of a prior credit =&gt; this error usually happened when your account don't have any SOL and you want to charge to it.
 check your from and feePayer has enough SOL. (you can use airdrop to get some)
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
