### ISSUE TITLE
Transfer NFT

### ISSUE THREAD

**Issue by rahulanand20** [blocto/solana-go-sdk#58]
Hi. I was trying to execute the transfer NFT functionality ... But continuously running into errors
 
**failed to send tx, err: rpc response error: {"code":-32002,"message":"Transaction simulation failed: Transaction loads a writable account that cannot be written","data":{"accounts":null,"err":"InvalidWritableAccount","logs":[],"unitsConsumed":0}}
exit status 1**

Could you give an example code for transfer like you have provided for Mint NFT? 
So that I can find out where I'm going wrong

**Comment by yihau** [comment]
how did you compose your transaction? could you paste your code here? (don't share any private in your code snippet)

**Comment by yihau** [comment]
1. you should use a token account as a `From` instead of a SOL address.
2. I'll more recommend you use `TransferChecked`. https://portto.github.io/solana-go-sdk/tour/token-transfer.html

**Comment by rahulanand20** [comment]
I tried to execute the example with taking this as a reference  nft (https://explorer.solana.com/address/Br5YJoiv63AdvzNM9YRb2onGdr7sSgi2a8zJyPz3R9ii?cluster=devnet)

**My error:-**
2022/06/20 22:57:44 send raw tx error, err: rpc response error: {"code":-32002,"message":"Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction","data":{"accounts":null,"err":{"InstructionError":[0,"InvalidAccountData"]},"logs":["Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]","Program log: Instruction: TransferChecked","Program log: Error: InvalidAccountData","Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1869 of 200000 compute units","Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA failed: invalid account data for instruction"],"unitsConsumed":0}}
exit status 1

**My code**
package main

import (
	"context"
	"log"

	"github.com/portto/solana-go-sdk/client"
	"github.com/portto/solana-go-sdk/common"
	"github.com/portto/solana-go-sdk/program/tokenprog"
	"github.com/portto/solana-go-sdk/rpc"
	"github.com/portto/solana-go-sdk/types"
)

// 7s6Ro1mBBmmKmP2QDT2zzuCMqS6AVCgBQi1mRnsjX4QG
var feePayer, _ = types.AccountFromBase58("")

// 43xqaQkf8N95Af64ZqafbcQsPWdKqy5BRWxH7FFYomqX
var alice, _ = types.AccountFromBase58("")

var mintPubkey = common.PublicKeyFromString("7FiJvym5YqWayshU2ngN9zw7J91DKko2hkXmgrajuMA3")

var aliceTokenRandomTokenPubkey = types.NewAccount()

var aliceTokenATAPubkey = types.NewAccount()

func main() {
	c := client.NewClient(rpc.DevnetRPCEndpoint)

	res, err := c.GetLatestBlockhash(context.Background())
	if err != nil {
		log.Fatalf("get recent block hash error, err: %v\n", err)
	}

	tx, err := types.NewTransaction(types.NewTransactionParam{
		Message: types.NewMessage(types.NewMessageParam{
			FeePayer:        feePayer.PublicKey,
			RecentBlockhash: res.Blockhash,
			Instructions: []types.Instruction{
				tokenprog.TransferChecked(tokenprog.TransferCheckedParam{
					From:     aliceTokenRandomTokenPubkey.PublicKey,
					To:       aliceTokenATAPubkey.PublicKey,
					Mint:     mintPubkey,
					Auth:     alice.PublicKey,
					Signers:  []common.PublicKey{},
					Amount:   1e8,
					Decimals: 8,
				}),
			},
		}),
		Signers: []types.Account{feePayer, alice},
	})
	if err != nil {
		log.Fatalf("failed to new tx, err: %v", err)
	}

	txhash, err := c.SendTransaction(context.Background(), tx)
	if err != nil {
		log.Fatalf("send raw tx error, err: %v\n", err)
	}

	log.Println("txhash:", txhash)
}

**Comment by yihau** [comment]
you should go through token account concept first. here give you some keypoints:

1. if you would like to transfer the NFT you memtioned
- mint: Br5YJoiv63AdvzNM9YRb2onGdr7sSgi2a8zJyPz3R9ii
- token account: DGJ6RsBxwGHbRfMRnTfZNbf7f8t3d86ou3Xg5PxwUdZu
- owner (auth): 7s6Ro1mBBmmKmP2QDT2zzuCMqS6AVCgBQi1mRnsjX4QG

2. you need to create a token account as a receiver. (https://portto.github.io/solana-go-sdk/tour/create-token-account.html) a token account transfer operation is from a token account to another token account

**Comment by rahulanand20** [comment]
Thanks, I tried to implement the code as you guided me but there is an error 

I have consider this example for transfer from

**Token Account**
**Address**	
DEdpuTdsSk5uBkALtiCZjLBzFUozpJ6nAdh8Vi937ppb
**Mint**	
Af415cxd67Jo4eQNzB2c7Zr5oCP9jBX4UJdt4XCW8vbf
**Owner**	
7s6Ro1mBBmmKmP2QDT2zzuCMqS6AVCgBQi1mRnsjX4QG

**To**
43xqaQkf8N95Af64ZqafbcQsPWdKqy5BRWxH7FFYomqX

**My code**

//43xqaQkf8N95Af64ZqafbcQsPWdKqy5BRWxH7FFYomqX
var feePayer, _ = types.AccountFromBase58("")

// 7s6Ro1mBBmmKmP2QDT2zzuCMqS6AVCgBQi1mRnsjX4QG
var alice, _ = types.AccountFromBase58("")

//token address
var mint = common.PublicKeyFromString("Af415cxd67Jo4eQNzB2c7Zr5oCP9jBX4UJdt4XCW8vbf")

//From Token Account Address	
var aliceTokenRandomTokenPubkey = common.PublicKeyFromString("DEdpuTdsSk5uBkALtiCZjLBzFUozpJ6nAdh8Vi937ppb")

//var aliceTokenATAPubkey = common.PublicKeyFromString("43xqaQkf8N95Af64ZqafbcQsPWdKqy5BRWxH7FFYomqX")

func main() {
	c := client.NewClient(rpc.DevnetRPCEndpoint)
	log.Println("feePayer", feePayer.PublicKey)
	log.Println("alice", alice.PublicKey)
	log.Println("mintPubkey", mint)
	log.Println("aliceTokenRandomTokenPubkey", aliceTokenRandomTokenPubkey)

	//mint := types.NewAccount()
	fmt.Printf("NFT: %v\n", mint)

	collection := types.NewAccount()
	fmt.Println(base58.Encode(collection.PrivateKey))
	fmt.Printf("collection: %v\n", collection.PublicKey.ToBase58())

	ata, _, err := common.FindAssociatedTokenAddress(feePayer.PublicKey, mint)
	if err != nil {
		log.Fatalf("failed to find a valid ata, err: %v", err)
	}

	tokenMetadataPubkey, err := tokenmeta.GetTokenMetaPubkey(mint)
	fmt.Println("tokenMetadataPubkey", tokenMetadataPubkey.ToBase58())

	if err != nil {
		log.Fatalf("failed to find a valid token metadata, err: %v", err)

	}
	tokenMasterEditionPubkey, err := tokenmeta.GetMasterEdition(mint)
	fmt.Println("tokenMasterEditionPubkey", tokenMasterEditionPubkey.ToBase58())

	if err != nil {
		log.Fatalf("failed to find a valid master edition, err: %v", err)
	}

	mintAccountRent, err := c.GetMinimumBalanceForRentExemption(context.Background(), tokenprog.MintAccountSize)
	if err != nil {
		log.Fatalf("failed to get mint account rent, err: %v", err)
	}

	res, err := c.GetLatestBlockhash(context.Background())
	if err != nil {
		log.Fatalf("get recent block hash error, err: %v\n", err)
	}

	tx, err := types.NewTransaction(types.NewTransactionParam{
		Message: types.NewMessage(types.NewMessageParam{
			FeePayer:        feePayer.PublicKey,
			RecentBlockhash: res.Blockhash,
			Instructions: []types.Instruction{
				sysprog.CreateAccount(sysprog.CreateAccountParam{
					From:     feePayer.PublicKey,
					New:      mint,
					Owner:    common.TokenProgramID,
					Lamports: mintAccountRent,
					Space:    tokenprog.MintAccountSize,
				}),

				tokenmeta.CreateMetadataAccountV2(tokenmeta.CreateMetadataAccountV2Param{
					Metadata:                tokenMetadataPubkey,
					Mint:                    mint,
					MintAuthority:           feePayer.PublicKey,
					Payer:                   feePayer.PublicKey,
					UpdateAuthority:         feePayer.PublicKey,
					UpdateAuthorityIsSigner: true,
					IsMutable:               true,
					Data: tokenmeta.DataV2{
						Name:                 "Fake SMS #1357",
						Symbol:               "FSMB",
						Uri:                  "https://bafybeibd6achyemgiqqz7ur54dm7eyslgugw5yuaop7pctb44dr5htlo3i.ipfs.infura-ipfs.io",
						SellerFeeBasisPoints: 100,
						Creators: &[]tokenmeta.Creator{
							{
								Address:  feePayer.PublicKey,
								Verified: true,
								Share:    100,
							},
						},
						Collection: &tokenmeta.Collection{
							Verified: false,
							Key:      collection.PublicKey,
						},
						Uses: &tokenmeta.Uses{
							UseMethod: tokenmeta.Burn,
							Remaining: 10,
							Total:     10,
						},
					},
				}),
				assotokenprog.CreateAssociatedTokenAccount(assotokenprog.CreateAssociatedTokenAccountParam{
					Funder:                 feePayer.PublicKey,
					Owner:                  feePayer.PublicKey,
					Mint:                   mint,
					AssociatedTokenAccount: ata,
				}),
				tokenprog.TransferChecked(tokenprog.TransferCheckedParam{
					From:     aliceTokenRandomTokenPubkey,
					To:       ata,
					Mint:     mint,
					Auth:     alice.PublicKey,
					Signers:  []common.PublicKey{},
					Amount:   1e8,
					Decimals: 8,
				}),
				tokenmeta.CreateMasterEditionV3(tokenmeta.CreateMasterEditionParam{
					Edition:         tokenMasterEditionPubkey,
					Mint:            mint,
					UpdateAuthority: feePayer.PublicKey,
					MintAuthority:   feePayer.PublicKey,
					Metadata:        tokenMetadataPubkey,
					Payer:           feePayer.PublicKey,
					MaxSupply:       pointer.Uint64(0),
				}),
			},
		}),
		Signers: []types.Account{feePayer, alice},
	})
	if err != nil {
		log.Fatalf("failed to new tx, err: %v", err)
	}

	txhash, err := c.SendTransaction(context.Background(), tx)
	if err != nil {
		log.Fatalf("send raw tx error, err: %v\n", err)
	}

	log.Println("txhash:", txhash)
}

**Comment by yihau** [comment]
this code is used to mint a NFT. please read the guide. you're still not get the main idea. `43xqaQkf8N95Af64ZqafbcQsPWdKqy5BRWxH7FFYomqX ` can't be a token receiver. you should create a token account then transfer token to the account.

**Comment by yihau** [comment]
1. if you don't use mintTo instruction, it means the new token which you created has 0 supply. I don't think there is anyone can do transfer cuz no one has the token.
2. what's the code snippet when you encountered `Unknown Token`?
3. a NFT is just a token, you can use token transfer to transfer it. you don't need to do with the metadata and master edition cuz they are related to the token.
4. could you please make your code more pretty and give them some meaningful name? I know you copy them from my docs, but it is a little hard to read if we would like to debug something.

**Comment by yihau** [comment]
if you would like to transfer the token `Af415cxd67Jo4eQNzB2c7Zr5oCP9jBX4UJdt4XCW8vbf`, you should replace all `mintNew.PublicKey` in your code with `common.PublicKeyFromString("Af415cxd67Jo4eQNzB2c7Zr5oCP9jBX4UJdt4XCW8vbf")`

**Comment by rahulanand20** [comment]
still error exists sir ..
 send raw tx error, err: rpc response error: {"code":-32002,"message":"Transaction simulation failed: Error processing Instruction 1: custom program error: 0x1","data":{"accounts":null,"err":{"InstructionError":[1,{"Custom":1}]},"logs":["Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1]","Program log: Create","Program 11111111111111111111111111111111 invoke [2]","Program 11111111111111111111111111111111 success","Program log: Initialize the associated token account","Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]","Program log: Instruction: InitializeAccount3","Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2933 of 387748 compute units","Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success","Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 15808 of 400000 compute units","Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success","Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]","Program log: Instruction: TransferChecked","Program log: Error: insufficient funds","Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2828 of 384192 compute units","Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA failed: custom program error: 0x1"],"unitsConsumed":15808}}
exit status 1

**Comment by yihau** [comment]
Amount = 1 Decimal = 0

**Comment by yihau** [comment]
error message said: `"Allocate: account Address { address: HyMy4khSDqaEHbHfgXgEanoKszGcZV11TJfLgV2KNBGE, base: None } already in use"`

if the account has already initialized, you can't create it again.

**Comment by rahulanand20** [comment]
Thanks sir. 
During Mint nft im getting this error

default: unable to Send Transaction%!(EXTRA *errors.errorString=rpc response error: {"code":-32002,"message":"Transaction simulation failed: Error processing Instruction 2: custom program error: 0xc","data":{"accounts":null,"err":{"InstructionError":[2,{"Custom":12}]},"logs":["Program 11111111111111111111111111111111 invoke [1]","Program 11111111111111111111111111111111 success","Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]","Program log: Instruction: InitializeMint","Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2586 of 1200000 compute units","Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success","Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1]","Program log: Instruction: Create Metadata Accounts v2","Program log: Transfer 5616720 lamports to the new account","Program 11111111111111111111111111111111 invoke [2]","Program 11111111111111111111111111111111 success","Program log: Allocate space for the account","Program 11111111111111111111111111111111 invoke [2]","Program 11111111111111111111111111111111 success","Program log: Assign the account to the owning program","Program 11111111111111111111111111111111 invoke [2]","Program 11111111111111111111111111111111 success","Program log: Symbol too long","Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 16467 of 1197414 compute units","Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: custom program error: 0xc"],"unitsConsumed":2586}})
E 2022-06-28T08:05:59.394254405Z [a2391a12-ba42-16fc-bd7c-0a54e9d3c800] default: {"errors":{"message":"Unable to Send Transaction","code":4002,"err":"rpc response error: {\"code\":-32002,\"message\":\"Transaction simulation failed: Error processing Instruction 2: custom program error: 0xc\",\"data\":{\"accounts\":null,\"err\":{\"InstructionError\":[2,{\"Custom\":12}]},\"logs\":[\"Program 11111111111111111111111111111111 invoke [1]\",\"Program 11111111111111111111111111111111 success\",\"Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]\",\"Program log: Instruction: InitializeMint\",\"Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2586 of 1200000 compute units\",\"Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success\",\"Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s invoke [1]\",\"Program log: Instruction: Create Metadata Accounts v2\",\"Program log: Transfer 5616720 lamports to the new account\",\"Program 11111111111111111111111111111111 invoke [2]\",\"Program 11111111111111111111111111111111 success\",\"Program log: Allocate space for the account\",\"Program 11111111111111111111111111111111 invoke [2]\",\"Program 11111111111111111111111111111111 success\",\"Program log: Assign the account to the owning program\",\"Program 11111111111111111111111111111111 invoke [2]\",\"Program 11111111111111111111111111111111 success\",\"Program log: Symbol too long\",\"Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s consumed 16467 of 1197414 compute units\",\"Program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s failed: custom program error: 0xc\"],\"unitsConsumed\":2586}}"}} {flow:"Order Entry" task:SolanaMintNft}
